source 'https://github.com/CocoaPods/Specs.git'    # 公有库地址

use_frameworks!
platform :ios, '8.0'

target 'WTYTextField_Example' do
  pod 'WTYTextField', :path => '../'

  target 'WTYTextField_Tests' do
    inherit! :search_paths

    
  end
end
